// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokMultiasset } from '../storyblok.d.ts';
export interface Carousel {
  assets: StoryblokMultiasset;
  styles?: unknown;
  mode?: "" | "slider" | "gallery" | "grid";
  overlay?: boolean;
  component: "carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface Columns {
  id?: string;
  body: (Text | Image | Wrapper)[];
  styles?: unknown;
  theme?: "" | "primary" | "secondary";
  margin?: "" | "slim" | "thick" | "screen";
  justify?: "" | "spaced" | "center" | "right";
  component: "columns";
  _uid: string;
  [k: string]: unknown;
}

export interface Cover {
  id?: string;
  body: (Text | Image | Link)[];
  image?: StoryblokAsset;
  styles?: unknown;
  theme?: "" | "primary" | "secondary";
  margin?: "" | "slim" | "thick" | "screen";
  justify?: "" | "left" | "center" | "right";
  dark?: boolean;
  blurred?: boolean;
  component: "cover";
  _uid: string;
  [k: string]: unknown;
}

export interface Field {
  id?: string;
  input?: {
    [k: string]: unknown;
  };
  label?: string;
  placeholder?: string;
  options?: {
    [k: string]: unknown;
  }[];
  component: "field";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  image?: StoryblokAsset;
  body?: Text[];
  copyright: string;
  terms: string;
  fixed?: boolean;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface Form {
  event: "" | "contact" | "download";
  lists?: ""[];
  label: string;
  fields?: (
    | Carousel
    | Columns
    | Cover
    | Field
    | Footer
    | Form
    | Header
    | Image
    | Link
    | Page
    | Post
    | Project
    | Steps
    | Text
    | Wrapper
  )[];
  settings?: unknown;
  display?: "" | "modal" | "drawer";
  identify?: boolean;
  messages?: unknown;
  success?: string;
  error?: string;
  component: "form";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  image?: StoryblokAsset;
  links?: Link[];
  fixed?: boolean;
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface Image {
  asset?: StoryblokAsset;
  styles?: unknown;
  width?: ("" | "1/3" | "1/2" | "2/3" | "1/1")[];
  size?: "" | "small" | "medium" | "large";
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  label: string;
  href: StoryblokMultilink;
  button?: boolean;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  header?: ISbStoryData<Header> | string;
  body?: (Cover | Carousel | Columns | Form)[];
  footer?: ISbStoryData<Footer> | string;
  meta?: unknown;
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Post {
  title: string;
  description: string;
  image?: StoryblokAsset;
  author?: string;
  body?: (Columns | Form)[];
  component: "post";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  title: string;
  description: string;
  image?: StoryblokAsset;
  author?: string;
  body?: (Cover | Carousel | Form | Columns)[];
  component: "project";
  _uid: string;
  [k: string]: unknown;
}

export interface Steps {
  id?: string;
  body?: Wrapper[];
  styles?: unknown;
  timeline?: boolean;
  component: "steps";
  _uid: string;
  [k: string]: unknown;
}

export interface Text {
  headline?: string;
  content?: string;
  styles?: unknown;
  width?: ("" | "1/3" | "1/2" | "2/3" | "1/1")[];
  size?: "" | "small" | "medium" | "large";
  justify?: "" | "spaced" | "center" | "right";
  component: "text";
  _uid: string;
  [k: string]: unknown;
}

export interface Wrapper {
  body?: (Text | Link | Image)[];
  styles?: unknown;
  mode?: "" | "card" | "accordion" | "menu";
  width?: {
    [k: string]: unknown;
  }[];
  component: "wrapper";
  _uid: string;
  [k: string]: unknown;
}
